export const BuildersData = [
    {
        id: 1,
        nickname: 'Pohor',
        position: 'Lead Builder',
        instagram: 'https://www.instagram.com/pohorek_builder/',
        photo: '/images/BuildersImages/pohor.png',
    },
    {
        id: 2,
        nickname: 'Wajt_',
        position: 'Builder',
        instagram: 'https://www.instagram.com/wajt_builder/',
        photo: '/images/BuildersImages/Wajt_.png',
    },
    {
        id: 3,
        nickname: 'Fstno',
        position: 'Builder',
        social: 'https://imgur.com/a/Ouk9b4a',
        photo: '/images/BuildersImages/Fstno.png',
    },
    {
        id: 4,
        nickname: '_yCoN_',
        position: 'Builder',
        social: 'https://ycon.crevado.com/my-work',
        instagram: 'https://www.instagram.com/ycon_1/',
        photo: '/images/BuildersImages/_yCoN_.jpg',
    },
    {
        id: 5,
        nickname: 'Suinzyyy',
        position: 'Builder',
        instagram: 'https://www.instagram.com/suinzyyy/',
        photo: '/images/BuildersImages/Suinzyyy.png',
    },
    {
        id: 6,
        nickname: 'Imbublifuk21',
        position: 'Builder',
        instagram: 'https://www.instagram.com/imbublifuk21_/',
        photo: '/images/BuildersImages/Imbublifuk21.png',
    },
    {
        id: 7,
        nickname: 'ItzzPhilip',
        position: 'Builder',
        instagram: 'https://www.instagram.com/itzzphilip/',
        photo: '/images/BuildersImages/ItzzPhilip.png',
    },
    {
        id: 8,
        nickname: 'Krysot',
        position: 'Builder',
        social: 'https://www.planetminecraft.com/member/krysot/',
        instagram: 'https://www.instagram.com/krysot_cz/',
        photo: '/images/BuildersImages/Krysot.png',
    },
    {
        id: 9,
        nickname: 'pmarqs',
        position: 'Builder',
        social: 'https://www.behance.net/rommue',
        photo: '/images/BuildersImages/pmarqs.png',
    },
    {
        id: 10,
        nickname: 'Chinasky',
        position: 'Builder',
        social: 'http://chinasky.tilda.ws/',
        photo: '/images/BuildersImages/Chinasky.png',
    },
    {
        id: 11,
        nickname: 'Shirokun003',
        position: 'Builder',
        social: 'https://www.artstation.com/shirokun003',
        photo: '/images/BuildersImages/Shirokun003.png',
    },
    {
        id: 12,
        nickname: 'KiRyaTryHARD',
        position: 'Builder',
        social: 'https://imgur.com/a/lvtE50g',
        photo: '/images/BuildersImages/KiRyaTryHARD.png',
    },
]
