export const BuildersData = [
    {
        id: 1,
        nickname: 'Pohor',
        position: 'Lead Builder',
        instagram: 'https://www.instagram.com/pohorek_builder/',
        photo: '/images/BuildersImages/pohor.png',
    },
    {
        id: 2,
        nickname: 'Wajt_',
        position: 'Builder',
        instagram: 'https://www.instagram.com/wajt_builder/',
        photo: '/images/BuildersImages/Wajt_.png',
    },
    {
        id: 3,
        nickname: 'Hyyzounn',
        position: 'Builder',
        social: 'https://hyyzounn.crevado.com/',
        instagram: 'https://www.instagram.com/hyyzounn/',
        photo: '/images/BuildersImages/Hyyzounn.png',
    },
    {
        id: 4,
        nickname: '_yCoN_',
        position: 'Builder',
        social: 'https://ycon.crevado.com/my-work',
        instagram: 'https://www.instagram.com/ycon_1/',
        photo: '/images/BuildersImages/_yCoN_.png',
    },
    {
        id: 5,
        nickname: 'Suinzyyy',
        position: 'Builder',
        instagram: 'https://www.instagram.com/suinzyyy/',
        photo: '/images/BuildersImages/Suinzyyy.png',
    },
    {
        id: 6,
        nickname: 'Imbublifuk21',
        position: 'Builder',
        instagram: 'https://www.instagram.com/imbublifuk21_/',
        photo: '/images/BuildersImages/Imbublifuk21.png',
    },
    {
        id: 7,
        nickname: 'ItzzPhilip',
        position: 'Builder',
        instagram: 'https://www.instagram.com/itzzphilip/',
        photo: '/images/BuildersImages/ItzzPhilip.png',
    },
]
